name: Maven CI/CD

on:
  push:
    branches: [master]
    tags: [v*]
  workflow_dispatch:

jobs:

  build_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Populate Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: sismics/ubuntu
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref_type != 'tag' }}
          labels: |
            org.opencontainers.image.title = Ubuntu Base Image for Teedy
            org.opencontainers.image.description = Teedy is an open source, lightweight document management system for individuals and businesses.
            org.opencontainers.image.created = ${{ github.event_created_at }}
            org.opencontainers.image.author = Sismics
            org.opencontainers.image.url = https://teedy.io/
            org.opencontainers.image.vendor = Sismics
            org.opencontainers.image.license = GPLv2
            org.opencontainers.image.version = ${{ github.event_head_commit.id }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}